### PR TITLE
Todo List 

### PR DESCRIPTION
**Pull request by Eshy10**
# Project: Todo List
Added : 
 - Default category that shows all todos
 - Category for each project
 - Forms to create a new Category and todos 
- Reset functions to clear all todos
- A delete option to delete a todo
- All todos to local storage

[Live Demo](https://elated-leakey-cd29e5.netlify.app/)

### CODE REVIEW

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @Eshy10 , @Spayco 
todo

Great job works great and fluidly
I really wanted to give a thumbs up until I looked at the code...It's very efficient but not well organised 

### [changes required]
- separate DOM from LOGIC [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png)]
You have DOM + logic mixed  in all your javascript files (except `notes.js`)

- We can see codes related to `PROJECTS` inside almost all your js files. It means code will be hard to debug. By this stage you should be implementing FACTORY FUNCTIONS and MODULES properly, please re-read that [chapter](https://www.theodinproject.com/courses/javascript/lessons/factory-functions-and-the-module-pattern) from ODIN PROJECT

I propose you to have a `DOM`, `project`, `notes/tasks` modules  etc.. [see example of code organisation [example](https://github.com/shloch/TODO_app/blob/master/src/todoModule.js)]

Good thing your code works...so let's get to organizing it

HAPPY CODING

**Comment by Eshy10** [comment]
The Dom elements are in modules which are in the navbar.js and content.js.. others will be kept in modules

**Comment by shloch** [comment]
Yes you are right...I also meant self contained modules..that is, a module handling one component of your app (example: 'PROJECT'  module) would be a good organisation and easy to debug ...... And best suits the concept of modules

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Changes Required❌.
# 🙋‍♂️ Team!!!
#### You did well addressing the issues raised earlier, however, there some flaws with the applications which we have to address to get the project approved🤗.
* [x] Currently, I able to enter an empty project and an empty todo, let us add input validations to the forms.
* [x] There should be a 'default' project ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- The default project should exist even if no project has been created yet.

**[OPTIONAL]**

* [ ] Kindly make it a habit to always add a description to the repo you create on Github.

### That is it kindly make these changes and submit a re-review🤗.
#### Happy coding👨‍💻
Addo Forison

**Comment by SpaYco** [comment]
@Forison, the empty ToDos isn't a bug, even [keep.google.com](https://keep.google.com) allow us to do it, and I don't think it's required to make that change, that being said, I will do it, 
for the 'default' project, that's the "all notes" tab, which shows all notes as stated in The Odin Project

**Review by shloch — APPROVED** [review]
## Hello @Eshy10 

accomplished

We're good to go...Great job with the good work

You get a thumbs up

**Pull request merged**
